# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import project.upload.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='', validators=[project.upload.validators.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
